export const countryData = {
    ad: { name: "Andorra", emoji: "🇦🇩" },
    ae: { name: "United Arab Emirates", emoji: "🇦🇪" },
    af: { name: "Afghanistan", emoji: "🇦🇫" },
    ag: { name: "Antigua and Barbuda", emoji: "🇦🇬" },
    ai: { name: "Anguilla", emoji: "🇦🇮" },
    al: { name: "Albania", emoji: "🇦🇱" },
    am: { name: "Armenia", emoji: "🇦🇲" },
    ao: { name: "Angola", emoji: "🇦🇴" },
    aq: { name: "Antarctica", emoji: "🇦🇶" },
    ar: { name: "Argentina", emoji: "🇦🇷" },
    as: { name: "American Samoa", emoji: "🇦🇸" },
    at: { name: "Austria", emoji: "🇦🇹" },
    au: { name: "Australia", emoji: "🇦🇺" },
    aw: { name: "Aruba", emoji: "🇦🇼" },
    ax: { name: "Aland Islands", emoji: "🇦🇽" },
    az: { name: "Azerbaijan", emoji: "🇦🇿" },
    ba: { name: "Bosnia and Herzegovina", emoji: "🇧🇦" },
    bb: { name: "Barbados", emoji: "🇧🇧" },
    bd: { name: "Bangladesh", emoji: "🇧🇩" },
    be: { name: "Belgium", emoji: "🇧🇪" },
    bf: { name: "Burkina Faso", emoji: "🇧🇫" },
    bg: { name: "Bulgaria", emoji: "🇧🇬" },
    bh: { name: "Bahrain", emoji: "🇧🇭" },
    bi: { name: "Burundi", emoji: "🇧🇮" },
    bj: { name: "Benin", emoji: "🇧🇯" },
    bl: { name: "Saint Barthelemy", emoji: "🇧🇱" },
    bm: { name: "Bermuda", emoji: "🇧🇲" },
    bn: { name: "Brunei Darussalam", emoji: "🇧🇳" },
    bo: { name: "Bolivia, Plurinational State of", emoji: "🇧🇴" },
    bq: { name: "Caribbean Netherlands", emoji: "🇧🇶" },
    br: { name: "Brazil", emoji: "🇧🇷" },
    bs: { name: "Bahamas", emoji: "🇧🇸" },
    bt: { name: "Bhutan", emoji: "🇧🇹" },
    bv: { name: "Bouvet Island", emoji: "🇧🇻" },
    bw: { name: "Botswana", emoji: "🇧🇼" },
    by: { name: "Belarus", emoji: "🇧🇾" },
    bz: { name: "Belize", emoji: "🇧🇿" },
    ca: { name: "Canada", emoji: "🇨🇦" },
    cc: { name: "Cocos (Keeling) Islands", emoji: "🇨🇨" },
    cd: { name: "Congo, the Democratic Republic of the", emoji: "🇨🇩" },
    cf: { name: "Central African Republic", emoji: "🇨🇫" },
    cg: { name: "Republic of the Congo", emoji: "🇨🇬" },
    ch: { name: "Switzerland", emoji: "🇨🇭" },
    ci: { name: "Ivory Coast", emoji: "🇨🇮" },
    ck: { name: "Cook Islands", emoji: "🇨🇰" },
    cl: { name: "Chile", emoji: "🇨🇱" },
    cm: { name: "Cameroon", emoji: "🇨🇲" },
    cn: { name: "China (People's Republic of China)", emoji: "🇨🇳" },
    co: { name: "Colombia", emoji: "🇨🇴" },
    cr: { name: "Costa Rica", emoji: "🇨🇷" },
    cu: { name: "Cuba", emoji: "🇨🇺" },
    cv: { name: "Cape Verde", emoji: "🇨🇻" },
    cw: { name: "Curacao", emoji: "🇨🇼" },
    cx: { name: "Christmas Island", emoji: "🇨🇽" },
    cy: { name: "Cyprus", emoji: "🇨🇾" },
    cz: { name: "Czech Republic", emoji: "🇨🇿" },
    de: { name: "Germany", emoji: "🇩🇪" },
    dj: { name: "Djibouti", emoji: "🇩🇯" },
    dk: { name: "Denmark", emoji: "🇩🇰" },
    dm: { name: "Dominica", emoji: "🇩🇲" },
    do: { name: "Dominican Republic", emoji: "🇩🇴" },
    dz: { name: "Algeria", emoji: "🇩🇿" },
    ec: { name: "Ecuador", emoji: "🇪🇨" },
    ee: { name: "Estonia", emoji: "🇪🇪" },
    eg: { name: "Egypt", emoji: "🇪🇬" },
    eh: { name: "Western Sahara", emoji: "🇪🇭" },
    er: { name: "Eritrea", emoji: "🇪🇷" },
    es: { name: "Spain", emoji: "🇪🇸" },
    et: { name: "Ethiopia", emoji: "🇪🇹" },
    eu: { name: "Europe", emoji: "🇪🇺" },
    fi: { name: "Finland", emoji: "🇫🇮" },
    fj: { name: "Fiji", emoji: "🇫🇯" },
    fk: { name: "Falkland Islands (Malvinas)", emoji: "🇫🇰" },
    fm: { name: "Micronesia, Federated States of", emoji: "🇫🇲" },
    fo: { name: "Faroe Islands", emoji: "🇫🇴" },
    fr: { name: "France", emoji: "🇫🇷" },
    ga: { name: "Gabon", emoji: "🇬🇦" },
    gb: { name: "United Kingdom", emoji: "🇬🇧" },
    gbeng: { name: "England", emoji: "🏴󠁧󠁢󠁥󠁮󠁧󠁿" },
    gbnir: { name: "Northern Ireland", emoji: "🇬🇧" },
    gbsct: { name: "Scotland", emoji: "🏴󠁧󠁢󠁳󠁣󠁴󠁿" },
    gbwls: { name: "Wales", emoji: "🏴󠁧󠁢󠁷󠁬󠁳󠁿" },
    gd: { name: "Grenada", emoji: "🇬🇩" },
    ge: { name: "Georgia", emoji: "🇬🇪" },
    gf: { name: "French Guiana", emoji: "🇬🇫" },
    gg: { name: "Guernsey", emoji: "🇬🇬" },
    gh: { name: "Ghana", emoji: "🇬🇭" },
    gi: { name: "Gibraltar", emoji: "🇬🇮" },
    gl: { name: "Greenland", emoji: "🇬🇱" },
    gm: { name: "Gambia", emoji: "🇬🇲" },
    gn: { name: "Guinea", emoji: "🇬🇳" },
    gp: { name: "Guadeloupe", emoji: "🇬🇵" },
    gq: { name: "Equatorial Guinea", emoji: "🇬🇶" },
    gr: { name: "Greece", emoji: "🇬🇷" },
    gs: { name: "South Georgia and the South Sandwich Islands", emoji: "🇬🇸" },
    gt: { name: "Guatemala", emoji: "🇬🇹" },
    gu: { name: "Guam", emoji: "🇬🇺" },
    gw: { name: "Guinea-Bissau", emoji: "🇬🇼" },
    gy: { name: "Guyana", emoji: "🇬🇾" },
    hk: { name: "Hong Kong", emoji: "🇭🇰" },
    hm: { name: "Heard Island and McDonald Islands", emoji: "🇭🇲" },
    hn: { name: "Honduras", emoji: "🇭🇳" },
    hr: { name: "Croatia", emoji: "🇭🇷" },
    ht: { name: "Haiti", emoji: "🇭🇹" },
    hu: { name: "Hungary", emoji: "🇭🇺" },
    id: { name: "Indonesia", emoji: "🇮🇩" },
    ie: { name: "Ireland", emoji: "🇮🇪" },
    il: { name: "Israel", emoji: "🇮🇱" },
    im: { name: "Isle of Man", emoji: "🇮🇲" },
    in: { name: "India", emoji: "🇮🇳" },
    io: { name: "British Indian Ocean Territory", emoji: "🇮🇴" },
    iq: { name: "Iraq", emoji: "🇮🇶" },
    ir: { name: "Iran, Islamic Republic of", emoji: "🇮🇷" },
    is: { name: "Iceland", emoji: "🇮🇸" },
    it: { name: "Italy", emoji: "🇮🇹" },
    je: { name: "Jersey", emoji: "🇯🇪" },
    jm: { name: "Jamaica", emoji: "🇯🇲" },
    jo: { name: "Jordan", emoji: "🇯🇴" },
    jp: { name: "Japan", emoji: "🇯🇵" },
    ke: { name: "Kenya", emoji: "🇰🇪" },
    kg: { name: "Kyrgyzstan", emoji: "🇰🇬" },
    kh: { name: "Cambodia", emoji: "🇰🇭" },
    ki: { name: "Kiribati", emoji: "🇰🇮" },
    km: { name: "Comoros", emoji: "🇰🇲" },
    kn: { name: "Saint Kitts and Nevis", emoji: "🇰🇳" },
    kp: { name: "Korea, Democratic People's Republic of", emoji: "🇰🇵" },
    kr: { name: "Korea, Republic of", emoji: "🇰🇷" },
    kw: { name: "Kuwait", emoji: "🇰🇼" },
    ky: { name: "Cayman Islands", emoji: "🇰🇾" },
    kz: { name: "Kazakhstan", emoji: "🇰🇿" },
    la: { name: "Laos (Lao People's Democratic Republic)", emoji: "🇱🇦" },
    lb: { name: "Lebanon", emoji: "🇱🇧" },
    lc: { name: "Saint Lucia", emoji: "🇱🇨" },
    li: { name: "Liechtenstein", emoji: "🇱🇮" },
    lk: { name: "Sri Lanka", emoji: "🇱🇰" },
    lr: { name: "Liberia", emoji: "🇱🇷" },
    ls: { name: "Lesotho", emoji: "🇱🇸" },
    lt: { name: "Lithuania", emoji: "🇱🇹" },
    lu: { name: "Luxembourg", emoji: "🇱🇺" },
    lv: { name: "Latvia", emoji: "🇱🇻" },
    ly: { name: "Libya", emoji: "🇱🇾" },
    ma: { name: "Morocco", emoji: "🇲🇦" },
    mc: { name: "Monaco", emoji: "🇲🇨" },
    md: { name: "Moldova, Republic of", emoji: "🇲🇩" },
    me: { name: "Montenegro", emoji: "🇲🇪" },
    mf: { name: "Saint Martin", emoji: "🇲🇫" },
    mg: { name: "Madagascar", emoji: "🇲🇬" },
    mh: { name: "Marshall Islands", emoji: "🇲🇭" },
    mk: { name: "North Macedonia", emoji: "🇲🇰" },
    ml: { name: "Mali", emoji: "🇲🇱" },
    mm: { name: "Myanmar", emoji: "🇲🇲" },
    mn: { name: "Mongolia", emoji: "🇲🇳" },
    mo: { name: "Macao", emoji: "🇲🇴" },
    mp: { name: "Northern Mariana Islands", emoji: "🇲🇵" },
    mq: { name: "Martinique", emoji: "🇲🇶" },
    mr: { name: "Mauritania", emoji: "🇲🇷" },
    ms: { name: "Montserrat", emoji: "🇲🇸" },
    mt: { name: "Malta", emoji: "🇲🇹" },
    mu: { name: "Mauritius", emoji: "🇲🇺" },
    mv: { name: "Maldives", emoji: "🇲🇻" },
    mw: { name: "Malawi", emoji: "🇲🇼" },
    mx: { name: "Mexico", emoji: "🇲🇽" },
    my: { name: "Malaysia", emoji: "🇲🇾" },
    mz: { name: "Mozambique", emoji: "🇲🇿" },
    na: { name: "Namibia", emoji: "🇳🇦" },
    nc: { name: "New Caledonia", emoji: "🇳🇨" },
    ne: { name: "Niger", emoji: "🇳🇪" },
    nf: { name: "Norfolk Island", emoji: "🇳🇫" },
    ng: { name: "Nigeria", emoji: "🇳🇬" },
    ni: { name: "Nicaragua", emoji: "🇳🇮" },
    // Add more countries similarly
};